"""Library-level V7 formal training primitives.

The package is deliberately independent of the historical ``scripts`` tree.
It provides explicit dependency injection for data preparation, model/loss,
optimization, validation, checkpointing, and diagnostics.  The V7 command
entrypoint assembles these pieces for a readiness fixture only.
"""

from .core import (
    ManualGradientDescent,
    StepResult,
    TrainingBatch,
    TrainingDependencies,
    TrainingState,
    V7FormalTrainer,
    block_until_ready,
    make_optimizer,
)
from .prepare import (
    build_v1_training_batches,
    build_v1_training_stats,
    load_selected_v1_examples,
)
from .p1i import (
    P1I_BATCH_CONTRACT,
    P1I_DATASET_ID,
    P1IPreparedData,
    atomic_training_checkpoint,
    build_p1i_batches,
    load_selected_p1i_examples,
    loss_fn_full,
    loss_fn_vanilla,
    make_gradient_transform,
    make_p1i_optimizer,
    model_apply_full,
    model_apply_vanilla,
    model_init_full,
    model_init_vanilla,
    prepare_p1i_data,
    tree_max_abs_difference,
    tree_parameter_count,
    tree_l2_norm,
    learning_rate_for_epoch,
)
from .evaluation import evaluate_level_a_validation
from .full_field import (
    FullFieldGeometry,
    FullFieldP1IData,
    load_alternative_p1i_examples,
    load_full_field_geometry,
    materialize_full_input_fields,
)
from .support import (
    CV_ONLY_PROVIDER,
    LAYOUT_AGNOSTIC_STRATIFIED_PROVIDER,
    SUPPORTED_ALTERNATIVE_PROVIDERS,
    SUPPORT_PROVIDER_SCHEMA_VERSION,
    SupportSelection,
    select_alternative_support,
    select_cv_only_support,
    select_layout_agnostic_stratified_support,
    support_provider_contract,
)

__all__ = [
    "ManualGradientDescent",
    "StepResult",
    "TrainingBatch",
    "TrainingDependencies",
    "TrainingState",
    "V7FormalTrainer",
    "block_until_ready",
    "make_optimizer",
    "build_v1_training_batches",
    "build_v1_training_stats",
    "load_selected_v1_examples",
    "P1I_BATCH_CONTRACT",
    "P1I_DATASET_ID",
    "P1IPreparedData",
    "atomic_training_checkpoint",
    "build_p1i_batches",
    "load_selected_p1i_examples",
    "loss_fn_full",
    "loss_fn_vanilla",
    "make_gradient_transform",
    "make_p1i_optimizer",
    "model_apply_full",
    "model_apply_vanilla",
    "model_init_full",
    "model_init_vanilla",
    "prepare_p1i_data",
    "tree_max_abs_difference",
    "tree_parameter_count",
    "tree_l2_norm",
    "learning_rate_for_epoch",
    "evaluate_level_a_validation",
    "FullFieldGeometry",
    "FullFieldP1IData",
    "load_alternative_p1i_examples",
    "load_full_field_geometry",
    "materialize_full_input_fields",
    "CV_ONLY_PROVIDER",
    "LAYOUT_AGNOSTIC_STRATIFIED_PROVIDER",
    "SUPPORTED_ALTERNATIVE_PROVIDERS",
    "SUPPORT_PROVIDER_SCHEMA_VERSION",
    "SupportSelection",
    "select_alternative_support",
    "select_cv_only_support",
    "select_layout_agnostic_stratified_support",
    "support_provider_contract",
]
