#!/usr/bin/env python3
"""Check the Heat3D v1 24-sample medium expansion smoke subset."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from rigno.heat3d_v1_label_diagnostics import diagnose_sample, find_sample_dirs  # noqa: E402
from rigno.heat3d_v1_reference_solver_v2 import BOTTOM_TOL_K, RESIDUAL_TOL  # noqa: E402


DEFAULT_SUBSET = (
    REPO_ROOT
    / "data"
    / "heat3d-thermal-simulation"
    / "subsets"
    / "v1_multilayer_bc_eq_physics_label_medium_expansion_v2"
)
DEFAULT_MANIFEST = REPO_ROOT / "configs" / "heat3d_v1_physics_label_medium_expansion_manifest.json"
POWER_REL_TOL = 1.0e-10
REQUIRED_FILES = (
    "coords.npy",
    "k_field.npy",
    "q_field.npy",
    "sample_meta.json",
    "temperature.npy",
    "label_meta.json",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check the 24-sample medium expansion physics-label smoke subset.")
    parser.add_argument("--subset", type=Path, default=DEFAULT_SUBSET)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    return parser.parse_args()


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"expected JSON object in {path}")
    return data


def _expected_samples(manifest_path: Path) -> list[dict[str, Any]]:
    manifest = _read_json(manifest_path)
    samples = manifest.get("samples", [])
    if not isinstance(samples, list):
        raise ValueError("manifest.samples must be a list")
    return [sample for sample in samples if isinstance(sample, dict)]


def _source_summary(sample_meta: dict[str, Any]) -> dict[str, Any]:
    summary = sample_meta.get("source_diagnostics")
    if not isinstance(summary, dict):
        raise ValueError("sample_meta.source_diagnostics missing or invalid")
    return summary


def _print_sample(report: dict[str, Any], sample_plan: dict[str, Any], source: dict[str, Any], label_meta: dict[str, Any]) -> None:
    temperature = report.get("temperature", {})
    print(
        "- "
        f"{report.get('sample_id')} split={report.get('split')} status={report.get('overall_status')} "
        f"source={sample_plan.get('source_pattern_tag')} "
        f"k={sample_plan.get('k_region_mode')} "
        f"stack={sample_plan.get('stack_template')} "
        f"bc={sample_plan.get('bc_category')} "
        f"T_range=[{temperature.get('T_min'):.6f}, {temperature.get('T_max'):.6f}] "
        f"source_missed={source.get('source_missed')} "
        f"active_volume={source.get('active_source_volume_discrete'):.6e} "
        f"integrated_power={source.get('integrated_q_power'):.6e} "
        f"power_rel_error={source.get('integrated_q_power_relative_error'):.6e} "
        f"converged={label_meta.get('convergence_flag')} "
        f"residual_norm={label_meta.get('residual_norm'):.6e} "
        f"bottom_error={label_meta.get('bottom_dirichlet_error'):.6e}"
    )


def main() -> int:
    args = parse_args()
    expected = _expected_samples(args.manifest)
    expected_by_id = {sample["sample_id"]: sample for sample in expected}
    expected_ids = [sample["sample_id"] for sample in expected]
    expected_split_counts = Counter(sample["split"] for sample in expected)

    sample_dirs = find_sample_dirs(args.subset)
    if not sample_dirs:
        print(f"ERROR: no medium/sample directories found under {args.subset}")
        print("No data were generated by this checker.")
        return 1

    observed_ids = [sample_dir.name for sample_dir in sample_dirs]
    errors: list[str] = []
    if observed_ids != expected_ids:
        errors.append(f"expected ids {expected_ids}, found {observed_ids}")

    reports = []
    source_summaries = []
    label_meta_summaries = []
    sample_plans = []
    for sample_dir in sample_dirs:
        for name in REQUIRED_FILES:
            if not (sample_dir / name).is_file():
                errors.append(f"{sample_dir.name} missing required file: {name}")
        if sample_dir.name not in expected_by_id:
            errors.append(f"{sample_dir.name} not found in manifest")
            continue
        if errors:
            continue
        sample_meta = _read_json(sample_dir / "sample_meta.json")
        label_meta = _read_json(sample_dir / "label_meta.json")
        source = _source_summary(sample_meta)
        if source.get("source_missed"):
            errors.append(f"{sample_dir.name} source_missed=true")
        if float(source.get("active_source_volume_discrete", 0.0)) <= 0.0:
            errors.append(f"{sample_dir.name} active_source_volume_discrete <= 0")
        if float(source.get("integrated_q_power_relative_error", 1.0)) > POWER_REL_TOL:
            errors.append(f"{sample_dir.name} integrated_q_power_relative_error exceeds tolerance")
        if label_meta.get("convergence_flag") is not True:
            errors.append(f"{sample_dir.name} convergence_flag is not true")
        if float(label_meta.get("residual_norm", 1.0)) > RESIDUAL_TOL:
            errors.append(f"{sample_dir.name} residual_norm exceeds tolerance")
        if float(label_meta.get("bottom_dirichlet_error", 1.0)) > BOTTOM_TOL_K:
            errors.append(f"{sample_dir.name} bottom_dirichlet_error exceeds tolerance")
        report = diagnose_sample(sample_dir)
        if report["overall_status"] == "fail":
            errors.append(f"{sample_dir.name} label diagnostics failed")
        reports.append(report)
        source_summaries.append(source)
        label_meta_summaries.append(label_meta)
        sample_plans.append(expected_by_id[sample_dir.name])

    print("Heat3D v1 physics-label medium expansion checker")
    print(f"subset: {args.subset}")
    print(f"manifest: {args.manifest}")
    print(f"expected_sample_count: {len(expected_ids)}")
    print("scope: 24-sample medium expansion smoke / benchmark-candidate planning diagnostic only")
    for report, plan, source, label_meta in zip(reports, sample_plans, source_summaries, label_meta_summaries):
        _print_sample(report, plan, source, label_meta)

    split_counts = Counter(report.get("split") for report in reports)
    source_pattern_counts = Counter(plan["source_pattern_tag"] for plan in sample_plans)
    k_region_counts = Counter(plan["k_region_mode"] for plan in sample_plans)
    stack_counts = Counter(plan["stack_template"] for plan in sample_plans)
    bc_counts = Counter(plan["bc_category"] for plan in sample_plans)
    fail_samples = [report.get("sample_id") for report in reports if report.get("overall_status") == "fail"]
    warning_samples = [report.get("sample_id") for report in reports if report.get("overall_status") == "warning"]
    print("summary")
    print(f"  expected_ids: {expected_ids}")
    print(f"  observed_ids: {observed_ids}")
    print(f"  expected_split_counts: {dict(expected_split_counts)}")
    print(f"  observed_split_counts: {dict(split_counts)}")
    print(f"  source_pattern_counts: {dict(source_pattern_counts)}")
    print(f"  k_region_mode_counts: {dict(k_region_counts)}")
    print(f"  stack_template_counts: {dict(stack_counts)}")
    print(f"  bc_category_counts: {dict(bc_counts)}")
    print(f"  source_missed_count: {sum(1 for item in source_summaries if item.get('source_missed'))}")
    print(f"  max_integrated_q_power_relative_error: {max((float(item.get('integrated_q_power_relative_error', 0.0)) for item in source_summaries), default=0.0):.6e}")
    print(f"  max_residual_norm: {max((float(item.get('residual_norm', 0.0)) for item in label_meta_summaries), default=0.0):.6e}")
    print(f"  max_bottom_dirichlet_error: {max((float(item.get('bottom_dirichlet_error', 0.0)) for item in label_meta_summaries), default=0.0):.6e}")
    print(f"  warning_samples: {warning_samples}")
    print(f"  fail_samples: {fail_samples}")
    print(f"  errors: {errors}")
    print("  diagnostics_scope: smoke diagnostics only; not formal physics validation")
    print(f"  medium_expansion_smoke_ok: {not errors}")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
