"""Create a tiny supervised v1 steady smoke subset with temperature targets.

This script copies a tiny subset of the existing metadata-first v1 samples and
adds `temperature.npy` generated by a minimal reference steady solver. It is
strictly for interface smoke validation, not for formal data generation.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import sys

import numpy as np


REPO_DIR = Path(__file__).resolve().parents[1]
if str(REPO_DIR) not in sys.path:
    sys.path.insert(0, str(REPO_DIR))

from rigno.heat3d_v1_reference_solver import solve_reference_temperature
from rigno.heat3d_v1_supervised import SUPERVISED_SUBSET_NAME, default_v1_supervised_samples_dir


SOURCE_SUBSET_NAME = "v1_multilayer_bc_eq_demo"
TARGET_SAMPLE_IDS = ("sample_000", "sample_005")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a tiny steady supervised v1 smoke subset with temperature targets."
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        default=(
            REPO_DIR / "data" / "heat3d-thermal-simulation" / "subsets" / SOURCE_SUBSET_NAME / "samples"
        ),
        help="Source metadata-only sample directory.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=default_v1_supervised_samples_dir(REPO_DIR),
        help="Output supervised smoke sample directory.",
    )
    return parser.parse_args()


def _update_meta(meta: dict, sample_id: str) -> dict:
    meta = dict(meta)
    meta["subset_name"] = SUPERVISED_SUBSET_NAME
    meta["stage"] = "supervised_smoke"
    meta["description"] = (
        f"{meta.get('description', '').strip()} "
        "This sample is part of a very small steady supervised smoke subset. "
        "temperature.npy is a PDE/reference-solver-derived supervision label used "
        "for interface-closure validation only."
    ).strip()
    generation_config = dict(meta.get("generation_config", {}))
    generation_config.update({
        "source_subset": SOURCE_SUBSET_NAME,
        "reference_solver": "rigno/heat3d_v1_reference_solver.py",
        "reference_solver_role": "minimal_reference_steady_solver_for_smoke_only",
        "temperature_role": "supervised_target",
        "dataset_role": "steady_supervised_smoke",
        "sample_scope": "very_small_interface_smoke_only",
    })
    meta["generation_config"] = generation_config
    validation = dict(meta.get("validation", {}))
    validation["expected_stage"] = "supervised_smoke"
    validation["temperature_required"] = True
    meta["validation"] = validation
    return meta


def write_supervised_sample(source_sample_dir: Path, target_sample_dir: Path) -> None:
    if target_sample_dir.exists():
        shutil.rmtree(target_sample_dir)
    shutil.copytree(source_sample_dir, target_sample_dir)

    meta_path = target_sample_dir / "sample_meta.json"
    meta = json.loads(meta_path.read_text())
    meta = _update_meta(meta, source_sample_dir.name)
    meta_path.write_text(json.dumps(meta, indent=2) + "\n")

    temperature = solve_reference_temperature(target_sample_dir)
    np.save(target_sample_dir / "temperature.npy", temperature)


def main() -> int:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for sample_id in TARGET_SAMPLE_IDS:
        source_sample_dir = args.source_dir / sample_id
        if not source_sample_dir.is_dir():
            raise FileNotFoundError(f"Missing source sample: {source_sample_dir}")
        target_sample_dir = args.output_dir / sample_id
        write_supervised_sample(source_sample_dir, target_sample_dir)
        written.append(target_sample_dir)

    print(f"Wrote {len(written)} supervised smoke sample(s) to {args.output_dir}")
    for sample_dir in written:
        print(f"  {sample_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
